ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastFailedLoginAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "loginBlockedUntil" TIMESTAMP(3);
